services:
  app:
    container_name: backend-prod
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - .:/app
    command: sleep infinity
    stdin_open: true
